-- MySQL Script generated by MySQL Workbench
-- Mon May 18 14:50:15 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `peluqueria` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `peluqueria` DEFAULT CHARACTER SET utf8 ;
USE `peluqueria` ;

-- -----------------------------------------------------
-- Table `mydb`.`CLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `peluqueria`.`CLIENTE` ;

CREATE TABLE IF NOT EXISTS `peluqueria`.`CLIENTE` (
  `idCLIENTE` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `telefono` INT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idCLIENTE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SERVICIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `peluqueria`.`SERVICIO` ;

CREATE TABLE IF NOT EXISTS `peluqueria`.`SERVICIO` (
  `idSERVICIO` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `precio` DECIMAL(10,2) NULL,
  `duracionMin` INT NULL,
  PRIMARY KEY (`idSERVICIO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUCTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `peluqueria`.`PRODUCTO` ;

CREATE TABLE IF NOT EXISTS `peluqueria`.`PRODUCTO` (
  `idPRODUCTO` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `stock` INT NULL,
  `precio` DECIMAL(10,2) NULL,
  PRIMARY KEY (`idPRODUCTO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PEDIDO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `peluqueria`.`PEDIDO` ;

CREATE TABLE IF NOT EXISTS `peluqueria`.`PEDIDO` (
  `idPEDIDO` INT NOT NULL,
  `fecha` DATE NULL,
  `CLIENTE_idCLIENTE` INT NOT NULL,
  PRIMARY KEY (`idPEDIDO`),
  INDEX `fk_PEDIDO_CLIENTE_idx` (`CLIENTE_idCLIENTE` ASC) VISIBLE,
  CONSTRAINT `fk_PEDIDO_CLIENTE`
    FOREIGN KEY (`CLIENTE_idCLIENTE`)
    REFERENCES `peluqueria`.`CLIENTE` (`idCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMPLEADO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `peluqueria`.`EMPLEADO` ;

CREATE TABLE IF NOT EXISTS `peluqueria`.`EMPLEADO` (
  `idEMPLEADO` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telefono` INT NULL,
  `salario` DECIMAL(10,2) NULL,
  `turno` SET('Manana', 'Tarde', 'Manana y Tarde') NOT NULL,
  `jefe` BOOLEAN NOT NULL,
  PRIMARY KEY (`idEMPLEADO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TICKET`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `peluqueria`.`TICKET` ;

CREATE TABLE IF NOT EXISTS `peluqueria`.`TICKET` (
  `idTICKET` INT NOT NULL,
  `metodoPago` ENUM('Efectivo', 'Tarjeta', 'Bizum', 'Transferencia') NOT NULL,
  `precioTotal` DECIMAL(10,2) NULL,
  `fechaPago` DATE NULL,
  `PEDIDO_idPEDIDO` INT NOT NULL,
  PRIMARY KEY (`idTICKET`),
  INDEX `fk_TICKET_PEDIDO1_idx` (`PEDIDO_idPEDIDO` ASC) VISIBLE,
  CONSTRAINT `fk_TICKET_PEDIDO1`
    FOREIGN KEY (`PEDIDO_idPEDIDO`)
    REFERENCES `peluqueria`.`PEDIDO` (`idPEDIDO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LINEA_PRODUCTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `peluqueria`.`LINEA_PRODUCTO` ;

CREATE TABLE IF NOT EXISTS `peluqueria`.`LINEA_PRODUCTO` (
  `PEDIDO_idPEDIDO` INT NOT NULL,
  `PRODUCTO_idPRODUCTO` INT NOT NULL,
  `idLineaProducto` INT NOT NULL,
  `cantidad` INT NULL,
  `precioUnitarioAplicado` DECIMAL(10,2) NULL,
  PRIMARY KEY (`PEDIDO_idPEDIDO`, `PRODUCTO_idPRODUCTO`, `idLineaProducto`),
  INDEX `fk_PEDIDO_has_PRODUCTO_PRODUCTO1_idx` (`PRODUCTO_idPRODUCTO` ASC) VISIBLE,
  INDEX `fk_PEDIDO_has_PRODUCTO_PEDIDO1_idx` (`PEDIDO_idPEDIDO` ASC) VISIBLE,
  CONSTRAINT `fk_PEDIDO_has_PRODUCTO_PEDIDO1`
    FOREIGN KEY (`PEDIDO_idPEDIDO`)
    REFERENCES `peluqueria`.`PEDIDO` (`idPEDIDO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEDIDO_has_PRODUCTO_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_idPRODUCTO`)
    REFERENCES `peluqueria`.`PRODUCTO` (`idPRODUCTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LINEA_SERVICIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `peluqueria`.`LINEA_SERVICIO` ;

CREATE TABLE IF NOT EXISTS `peluqueria`.`LINEA_SERVICIO` (
  `SERVICIO_idSERVICIO` INT NOT NULL,
  `PEDIDO_idPEDIDO` INT NOT NULL,
  `idLineaServicio` INT NOT NULL,
  `horaInicio` DATETIME NULL,
  `precioUnitarioAplicado` DECIMAL(10,2) NULL,
  `EMPLEADO_idEMPLEADO` INT NOT NULL,
  PRIMARY KEY (`SERVICIO_idSERVICIO`, `PEDIDO_idPEDIDO`, `idLineaServicio`),
  INDEX `fk_SERVICIO_has_PEDIDO_PEDIDO1_idx` (`PEDIDO_idPEDIDO` ASC) VISIBLE,
  INDEX `fk_SERVICIO_has_PEDIDO_SERVICIO1_idx` (`SERVICIO_idSERVICIO` ASC) VISIBLE,
  INDEX `fk_LINEA_SERVICIO_EMPLEADO1_idx` (`EMPLEADO_idEMPLEADO` ASC) VISIBLE,
  CONSTRAINT `fk_SERVICIO_has_PEDIDO_SERVICIO1`
    FOREIGN KEY (`SERVICIO_idSERVICIO`)
    REFERENCES `peluqueria`.`SERVICIO` (`idSERVICIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SERVICIO_has_PEDIDO_PEDIDO1`
    FOREIGN KEY (`PEDIDO_idPEDIDO`)
    REFERENCES `peluqueria`.`PEDIDO` (`idPEDIDO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LINEA_SERVICIO_EMPLEADO1`
    FOREIGN KEY (`EMPLEADO_idEMPLEADO`)
    REFERENCES `peluqueria`.`EMPLEADO` (`idEMPLEADO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;